version: 0.2

phases:
  install:
    commands:
      - echo "Starting build..."
  build:
    commands:
      - echo "Copying files to S3..."
      - aws s3 cp . s3://awbucket1807/demo/ --recursive

artifacts:
  files:
    - '**/*'
